services:
  django:
    image: django
    container_name: django-container
    command: python manage.py runserver 127.0.0.0.0:8000
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      ./.env
    ports:
      - 8001:8000
    volumes:
      - .:/app
